### ISSUE TITLE
Weights

### ISSUE THREAD

**Issue by KrunalDatascience** [bennycheung/Food100_YOLO_Tools#4]
Hey, can you please share the weights of your trained model? Thanka!

**Comment by bennycheung** [comment]
Thanks for the interest on food detection! If you kindly share the purpose of your usage, I would love to share the trained weights with you.

Benny Cheung


On Jun 1, 2019, at 1:06 PM, KrunalDatascience <notifications@github.com> wrote:

Hey, can you please share the weights of your trained model? Thanka!

**Comment by KrunalDatascience** [comment]
Hi Benny, I am working on a summer project related to some fast food and drinks identification in a image. I wanted to try you weights and see how it is working for me.

**Comment by bennycheung** [comment]
Thanks for sharing your plan. I hope you can compare different methods to complete your project!
Here is the link to my trained weight file, which is YOLOv2 https://drive.google.com/open?id=1T25Vjn6LmA3c6WLRvcsgfG8ndwP-eT8m

Please download the file within 24 hours, then the weight file will be removed from download.
Let me know your success stories! Enjoy.

**Comment by bennycheung** [comment]
The weights link has been shared.
